//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_MovieList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string ServerLocation_ { get; set; }
        public string DBgenres { get; set; }
        public string DBid { get; set; }
        public string DBTitle { get; set; }
        public string DBposter { get; set; }
    
        public virtual Info Info { get; set; }
    }
}
